cc_binary(
    name = "example_cpp",
    srcs = ["example.cpp"],
    deps = [
        "//third_party/boost:boost",
        "@com_google_absl//absl/strings",
        "@com_github_fmtlib_fmt//:fmt",
    ],
)
